/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ReturnedBookResponse } from '../models/returned-book-response';
export interface PageResponseReturnedBookResponse {
  content?: Array<ReturnedBookResponse>;
  first?: boolean;
  last?: boolean;
  pageNumber?: number;
  pageSize?: number;
  totalElements?: number;
  totalPages?: number;
}
